level = 1
attacks = ["scratch"]
spells = []
speed = 12

[nouns]
name = "Aris"
proper_name = true
pronouns = "Male"

[bases]
heart = 30
soul = 10
power = 6
defense = 5
magic = 1
resistance = 7

[growths]
heart = 100
soul = 80
power = 80
defense = 75
magic = 60
resistance = 50

[skillset]
major = "Negative"
minor = "Chaos"
