level = 1
attacks = ["scratch"]
spells = []
speed = 12

[nouns]
name = "Aris"
proper_name = true
pronouns = "Male"

[stats]
heart = 30
soul = 10
power = 6
defense = 5
magic = 1
resistance = 7

[skillset]
major = "Negative"
minro = "Choas"
