level = 1
spells = ["magic_missile"]
attacks = ["scratch", "bite"]
speed = 12

[nouns]
name = "Luvui"
proper_name = true
pronouns = "Female"

[stats]
heart = 30
soul = 15
power = 3
defense = 6
magic = 6
resistance = 3

[skillset]
major = "Chaos"
minor = "Positive"
