level = 1
attacks = ["scratch", "bite"]
spells = ["magic_missile", "debug/level_up", "debug/change_affinity"]
speed = 12
icon = "luvui"

on_consider = "consider/characters/basic"

[nouns]
name = "Luvui"
proper_name = true
pronouns = "Female"

[bases]
heart = 30
soul = 15
power = 3
defense = 6
magic = 6
resistance = 3

[growths]
heart = 100
soul = 100
power = 40
defense = 50
magic = 80
resistance = 40

[skillset]
major = "Chaos"
minor = "Positive"
