[package]
name = "esprit2"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1.1.2"
alua = { version = "0.1.3", features = ["userdata"] }
grid = { version = "0.14.0", features = ["serde"] }
mlua = { version = "0.9.8", features = ["luajit", "serialize", "vendored"] }
paste = "1.0.14"
pest = "2.7.10"
pest_derive = "2.7.10"
rand = "0.8.5"
sdl2 = { version = "0.37.0", features = ["image", "ttf", "gfx"] }
serde = { version = "1.0.196", features = ["derive", "rc"] }
thiserror = "1.0.57"
toml = "0.8.10"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "serde"] }
