[package]
name = "esprit2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grid = { version = "0.13.0", features = ["serde"] }
lazy_static = "1.4.0"
paste = "1.0.14"
sdl2 = { version = "0.36.0", features = ["image", "ttf"] }
serde = { version = "1.0.196", features = ["derive"] }
toml = "0.8.10"
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "serde"] }
