[package]
name = "esprit2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
sdl2 = { version = "0.36.0", features = ["bundled", "image"] }
serde = { version = "1.0.196", features = ["derive"] }
toml = "0.8.10"
