[package]
name = "esprit2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.1.2"
grid = { version = "0.13.0", features = ["serde"] }
lazy_static = "1.4.0"
paste = "1.0.14"
rand = "0.8.5"
sdl2 = { version = "0.36.0", features = ["image", "ttf"] }
serde = { version = "1.0.196", features = ["derive"] }
thiserror = "1.0.57"
toml = "0.8.10"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "serde"] }
