name = "Magic Missile"
icon = "magic_missile"

energy = "Positive"
harmony = "Chaos"

level = 1
magnitude = "magic + 4"
pierce_threshold = 2

[on_cast]
type = "Path"
source = "scripts/spells/magic_missile.lua"
