name = "Magic Missile"
description = "Constructs a searing ray of magical energy that can be fired at a target."
icon = "magic_missile"

energy = "Negative"
harmony = "Order"

level = 1

on_cast = "spells/magic_missile"
on_input = "input/single_target"
on_consider = "consider/spells/magic_missile"

[parameters]
magnitude = "magic + 4"
pierce_threshold = 2
range = 5
cast_time = 12

