name = "Swap"
description = "Swaps the caster's position with the target. For non-allied targets, the spell must have a magnitude greater than the target's resistance."
# TODO: Swap icon
icon = "magic_missile"

# This perfectly matches Luvui's affinity, making it a good early game spell for her.
energy = "Positive"
harmony = "Chaos"

level = 4

on_cast = "spells/swap"
# TODO: Allow movement heuristics to apply to characters other than the considerer, making swap usable by npcs
#on_consider = "consider/spells/swap"
on_input = "input/single_target"

[parameters]
# Feel free to change this value as needed, it's set to an arbitrary value to test the resistance code.
magnitude = "magic"
# TODO: pick a good range value. expression ranges would allow this to vary based on magic, eg: magic / 2 (within 4 to 8)
range = 8
# Long cast time to punish risky swaps
cast_time = 48

