name = "(DEBUG) Affinity: Negative Chaos"
description = "Changes the target's magical affinity"
icon = "dummy"

energy = "Positive"
harmony = "Order"

level = 0

[parameters]
range = 5

[on_cast]
type = "Inline"
source = '''
return coroutine.create(function()
	local target = coroutine.yield({ type = "Cursor", x = caster.x, y = caster.y, range = parameters.range })
  target:force_affinity(6);
  Console:print(target:replace_nouns("{Address}'s affinity is now Negative Chaos"))
end)
'''
