name = "Scratch"
damage = "5"
weight = 100

[messages]
high = [
	# Having a few of these makes it a little more common.
	"{self_Address}'s claws rake against {target_address}",
	"{target_Address} is struck by {self_address}'s claws",
	"{self_Address} grazes {target_address} with {self_their} claws",
	"{self_Address} strikes {target_address} with {self_their} claws",
	"{self_Address} digs {self_their} claws into {target_address}",
]
low = [
	"{self_Address}'s claws barely missed {target_address}",
	"{target_Address} was tickled by {self_address}'s claws",
	"{self_Address}'s claws lightly slid across {target_address}",
]
