name = "(DEBUG) Change Affinity"
description = "Changes the target's magical affinity"
icon = "dummy"

energy = "Positive"
harmony = "Order"

level = 0

on_cast = "spells/debug/change_affinity"

[parameters]
range = 5
