name = "(DEBUG) Level Up"
icon = "dummy"

energy = "Positive"
harmony = "Order"

level = 0

[parameters]
type = "Target"

[on_cast]
type = "Inline"
source = '''
return coroutine.create(function()
	local target = coroutine.yield({ type = "Cursor", x = caster.x, y = caster.y, range = 10 })
  target:force_level();
  Console:print(target:replace_nouns("{Address}'s level increased to "..target.sheet.level))
end)
'''
