name = "(DEBUG) Level Up"
description = "Causes the targeted character to gain a level."
icon = "dummy"

energy = "Positive"
harmony = "Order"

level = 0

on_cast = "spells/debug/level_up"
on_input = "input/single_target"

[parameters]
range = 5
