[ui]
pamphlet_width = 400
console_height = 200
normal_mode_color = [119, 231, 162]
cast_mode_color = [162, 119, 231]
cursor_mode_color = [231, 162, 119]
font_size = 18

[controls]
left = ["H", "Left", "Keypad 4"]
right = ["L", "Right", "Keypad 6"]
up = ["K", "Up", "Keypad 8"]
down = ["J", "Down", "Keypad 2"]
up_left = ["Y", "Keypad 7"]
up_right = ["U", "Keypad 9"]
down_left = ["B", "Keypad 1"]
down_right = ["N", "Keypad 3"]
talk = ["T"]
cast = ["Z"]
underfoot = ["."]
confirm = ["Return"]
escape = ["Escape"]
